# Generated by Django 4.1.4 on 2023-01-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moofs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moof",
            name="image",
            field=models.FileField(
                blank=True, default="None", null=True, upload_to="images/"
            ),
        ),
    ]
