# Generated by Django 4.1.4 on 2023-01-13 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moofs", "0003_alter_moof_image_alter_moof_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moof",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
