# Generated by Django 4.1.4 on 2023-01-13 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moofs", "0004_alter_moof_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moof",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="moof",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
