# Generated by Django 4.1.4 on 2023-01-19 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moofs", "0005_alter_moof_image_alter_moof_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="moof",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MoofLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "moof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="moofs.moof"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="moof",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="moof_user",
                through="moofs.MoofLike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
