# Generated by Django 4.1.4 on 2023-01-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moofs", "0006_moof_timestamp_mooflike_moof_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="moof",
            name="parent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="moofs.moof"
            ),
        ),
    ]
